// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxa9_ziMLbIAIbHjiajhnUsN6lw0wgZuY',
    appId: '1:279849595327:web:c5bde445e35dec340b710a',
    messagingSenderId: '279849595327',
    projectId: 'm-a-11-11',
    authDomain: 'm-a-11-11.firebaseapp.com',
    storageBucket: 'm-a-11-11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkgL67MjgjvfUlyn1OpN38zvWAd8S294Q',
    appId: '1:279849595327:android:1106a7d66c69dbb20b710a',
    messagingSenderId: '279849595327',
    projectId: 'm-a-11-11',
    storageBucket: 'm-a-11-11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC55wh30gTD8LjAivT0yf0DOterr60MO5U',
    appId: '1:279849595327:ios:c74adff8c9adf6b20b710a',
    messagingSenderId: '279849595327',
    projectId: 'm-a-11-11',
    storageBucket: 'm-a-11-11.firebasestorage.app',
    iosBundleId: 'com.masha1111.coupleworld',
  );
}
